/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas4;

import com.mysql.jdbc.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author andrew
 */
public class Cuaca extends javax.swing.JFrame {
        //PANDUAN KONEKSI KOTA DAN TANGGAL = https://www.youtube.com/watch?v=uuhEb0k3vVE
    /**
     * Creates new form FormCuaca
     */
    public Cuaca() {
        initComponents();
            
            
    }
    /*public class Function{
        Connection con = getConnection();
        ResultSet rs = null;
        PreparedStatement pst = null;
        public ResultSet find(String x){
            try{
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/data_cuaca", "root", "");        //Buat Function
                pst = con.prepareStatement("SELECT * FROM  t_cuaca where nama_kota=?");
                pst.setString(1, hasilKota.getText());
                rs = pst.executeQuery();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            return rs;
            
        }
        
        
    }*/
    /*public void Imgage() {
            String a = Maks.getText();
            int b = Integer.parseInt(a);
            if(b <= 25){
                JLabel label = new JLabel(new ImageIcon("src/tugas4/cerah.jpg"));
            }else if(b >= 25 && b <=35){
                JLabel label = new JLabel(new ImageIcon("src/tugas4/mendung.jpg"));         //Buat Gambar
            }else if(b >= 36){
                JLabel label = new JLabel(new ImageIcon("src/tugas4/hujan.jpg"));
            }else{
            }
    }*/
    /*public class PanelBackground extends JPanel{
    private Image image;
 
    public PanelBackground() {
        image = new ImageIcon(getClass().getResource("src/tugas4/hujan.jpg")).getImage();
    }
 
    @Override
    protected void paintComponent(Graphics grphcs) {                                    //Buat Gambar
        super.paintComponent(grphcs);
 
        Graphics2D gd = (Graphics2D) grphcs.create();
        gd.drawImage(image, 0, 0, getWidth(), getHeight(), null);
        gd.dispose();
    }
    }*/
    
    /**
     *
     * @return 
     */
   
    public Connection getConnection() {
    
    Connection con;
    try{
        con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/data_cuaca", "root", "");
        return con;
    }catch(SQLException e){
        return null; 
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        monitorCuaca = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textIcon = new javax.swing.JLabel();
        copyHari = new javax.swing.JLabel();
        hasilSuhu = new javax.swing.JLabel();
        Maks = new javax.swing.JLabel();
        Min = new javax.swing.JLabel();
        Angin = new javax.swing.JLabel();
        Lembap = new javax.swing.JLabel();
        Tekanan = new javax.swing.JLabel();
        kalender = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        hasilCuaca = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblGambar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hasilKota = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setTitle("Monitor Cuaca");
        setBackground(new java.awt.Color(255, 0, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monitorCuaca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        monitorCuaca.setText("Monitor Cuaca");
        jPanel1.add(monitorCuaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 15, 230, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Suhu Maksimum");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 98, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Suhu Minimum");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 119, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Kecepatan Angin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 142, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Kelembapan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 165, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Tekanan Udara");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 189, -1, -1));

        textIcon.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        textIcon.setText("                       ");
        jPanel1.add(textIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 186, -1, -1));

        copyHari.setText("         ");
        jPanel1.add(copyHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, -1));

        hasilSuhu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        hasilSuhu.setText("    ");
        jPanel1.add(hasilSuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 73, 121, -1));

        Maks.setText("   ");
        jPanel1.add(Maks, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 96, 66, -1));

        Min.setText("       ");
        jPanel1.add(Min, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 117, 66, -1));

        Angin.setText("         ");
        jPanel1.add(Angin, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 140, 66, -1));

        Lembap.setText("       ");
        jPanel1.add(Lembap, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 163, 66, -1));

        Tekanan.setText("    ");
        jPanel1.add(Tekanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 187, 66, -1));

        kalender.setDateFormatString("yyyy-MM-dd");
        kalender.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                kalenderPropertyChange(evt);
            }
        });
        jPanel1.add(kalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 15, 138, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Kondisi Cuaca");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 213, 86, -1));

        hasilCuaca.setText("     ");
        jPanel1.add(hasilCuaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 211, 66, -1));

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 245, -1, -1));
        jPanel1.add(lblGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 124, 115, 55));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Kota");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 23, -1, -1));

        hasilKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilKotaActionPerformed(evt);
            }
        });
        getContentPane().add(hasilKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 21, 320, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas4/Background3.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 370));

        jMenuBar2.setBackground(new java.awt.Color(51, 255, 255));

        jMenu4.setText("File");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Help");

        menuExit.setText("Help");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu5.add(menuExit);

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu5.add(menuAbout);

        jMenuBar2.add(jMenu5);

        jMenu1.setText("Input");

        jMenuItem1.setText("Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Data");

        jMenuItem2.setText("Data");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        FormHelp help = new FormHelp();
        help.setVisible(true);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Aplikasi Monitoring Cuaca" + "\n Andrew S.C Manurung" + "\n NIM 1641913");
    }//GEN-LAST:event_menuAboutActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        System.exit(-1);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       FormUser input = new FormUser();
       input.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FormData input = new FormData();
        input.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = getConnection();
            String nama_kota = hasilKota.getText();
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = fmt.format(kalender.getDate());

            Statement st = con.createStatement();
            String query = "SELECT * FROM t_cuaca WHERE nama_kota = '" + nama_kota +"' "
            + "AND tanggal = '" + tanggal + "%' "
            + "LIMIT 1";
            ResultSet rs = st.executeQuery(query);
            while(rs.next()){

                SimpleDateFormat fmt2 = new SimpleDateFormat("dd MMMM YYYY", Locale.forLanguageTag("Id"));
                copyHari.setText(fmt2.format(kalender.getDate()));
                hasilSuhu.setText(rs.getString("suhu")+" "+(char)0x00B0+" C");
                monitorCuaca.setText("Cuaca di "+rs.getString("nama_kota"));
                Maks.setText(rs.getString("suhu_maks")+" "+(char)0x00B0+" C");
                Min.setText(rs.getString("suhu_min")+" "+(char)0x00B0+" C");
                Angin.setText(rs.getString("kecepatan_angin")+" m/s");
                Lembap.setText(rs.getString("kelembapan")+" %");
                Tekanan.setText(rs.getString("tekanan_udara")+" hPa");
                hasilCuaca.setText(rs.getString("kondisi_cuaca"));
                String gambar = rs.getString("gambar");
                lblGambar.setIcon(new javax.swing.ImageIcon("E:\\KULIAH STMIK\\Pemrograman Visual\\UasModel\\src\\Picture\\"+gambar));
                    textIcon.setText(rs.getString("kondisi_cuaca"));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Harap isi Kota dan Tanggal sesuai data yang ada");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kalenderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kalenderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_kalenderPropertyChange

    private void hasilKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilKotaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Angin;
    private javax.swing.JLabel Lembap;
    private javax.swing.JLabel Maks;
    private javax.swing.JLabel Min;
    private javax.swing.JLabel Tekanan;
    private javax.swing.JLabel copyHari;
    private javax.swing.JLabel hasilCuaca;
    private javax.swing.JTextField hasilKota;
    private javax.swing.JLabel hasilSuhu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser kalender;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JLabel monitorCuaca;
    private javax.swing.JLabel textIcon;
    // End of variables declaration//GEN-END:variables
}
