/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas4;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author andrew
 */
public class FormUser extends javax.swing.JFrame {

    /**
     * Creates new form FormUser
     */
    public FormUser() {
        initComponents();
    }
    public Connection getConnection() {
    
    Connection con;
    try{
        con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/data_cuaca", "root", "");
        return con;
    }catch(SQLException e){
        return null; 
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        User = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Data User");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 78, 75, -1));

        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 118, 75, -1));
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 75, 147, -1));

        login.setBackground(new java.awt.Color(51, 255, 255));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 155, -1, -1));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 115, 147, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas4/Background5.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = getConnection();
       String password;
       password = new String(Password.getPassword());
       String id = User.getText();
            
       Statement stat = con.createStatement();
       ResultSet rs =stat.executeQuery("SELECT * FROM t_login WHERE Nama='" + id + "'"+"and Password='"+password+"'");
       if(rs.next()){
                if(rs.getString("Value").equals("admin")){
                    FormInputData admin = new FormInputData();
                    admin.setVisible(true);
                    this.dispose();
                }else if(rs.getString("Value").equals("user")){
                    FormInputDataUser user = new FormInputDataUser();
                    user.setVisible(true);
                    this.dispose();
                }
       }else{
           JOptionPane.showMessageDialog(null, "Login Gagal");
           User.setText("");
           Password.setText("");
           User.requestFocus();
          }
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    // End of variables declaration//GEN-END:variables
}
