/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas4;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
/**
 *
 * @author andrew
 */
public class FormInputDataUser extends javax.swing.JFrame {

    

    /**
     * Creates new form FormInputData
     */
    
    
    public FormInputDataUser() {
        initComponents();
        /*add(inputData);
        
        inputData.addActionListener(new ActionListener(){
            
            public void actionPerformed(ActionEvent e) {
                try{
                    theQuery("Insert into data_cuaca (date,nama_kota,suhu,suhu_maks,suhu_min,kecepatan_angin,kelembapan,tekan) values ('"+txtTanggal.getText()+"','"+txtNama.getText()+"','"+txtSuhu.getText()+"',"
                            + "'"+txtMaks.getText()+"','"+txtMin.getText()+"','"+txtLembap.getText()+"',"
                                    + "'"+txtAngin.getText()+"','"+txtUdara.getText()+")");
                    }catch (Exception ex){
            
                    }
            }
            
                
        });*/
    }
        
        
    
    
    public Connection getConnection() {
    Connection con;
    
    try{
        con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/data_cuaca", "root", "");
        return con;
    }catch(SQLException e){
        return null; 
    }
    }
    /*public void theQuery (String query){
        
        
        
    }*/
    
    /*public ArrayList<User> usersList(){
        
        ArrayList<User> usersList = new ArrayList<User>();
        Connection connection = getConnection();
        
        String query = "SELECT * FROM `t_cuaca`";
        Statement st;
        ResultSet rs;
        try {
            st = (Statement) connection.createStatement();
            rs = st.executeQuery(query);
            User user;
            while(rs.next()){
                user = new User(rs.getTimestamp("date"),rs.getString("nama_kota"),rs.getDouble("suhu"),
                        rs.getDouble("suhu_maks"),rs.getDouble("suhu_min"),rs.getDouble("kecepatan_angin"),
                        rs.getDouble("kelembapan"),rs.getDouble("tekan"));
                usersList.add(user);
            }    
            JOptionPane.showMessageDialog(null, "Berhasil Di Input");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erorr");
        }
        return usersList;
    }*/
    
    
    
    /**
     *
     */
    
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtSuhu = new javax.swing.JTextField();
        txtMaks = new javax.swing.JTextField();
        txtMin = new javax.swing.JTextField();
        txtLembap = new javax.swing.JTextField();
        txtAngin = new javax.swing.JTextField();
        txtUdara = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        txtKalender = new com.toedter.calendar.JDateChooser();
        status = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnGambar = new javax.swing.JButton();
        gambar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setTitle("Input Data Cuaca");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Input Data Cuaca");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel2.setText("Tanggal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 73, -1, -1));

        jLabel3.setText("Nama Kota");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 105, -1, -1));

        jLabel4.setText("Suhu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 140, -1, -1));

        jLabel5.setText("Suhu Maks");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jLabel6.setText("Suhu Min");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 210, -1, -1));

        jLabel7.setText("Kelembapan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 245, -1, -1));

        jLabel8.setText("Kecepatan Angin");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 280, -1, -1));

        jLabel9.setText("Tekanan Udara");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 315, -1, -1));

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 102, 145, -1));
        getContentPane().add(txtSuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 137, 145, -1));
        getContentPane().add(txtMaks, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 172, 145, -1));
        getContentPane().add(txtMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 207, 145, -1));
        getContentPane().add(txtLembap, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 242, 145, -1));
        getContentPane().add(txtAngin, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 277, 145, -1));
        getContentPane().add(txtUdara, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 312, 145, -1));

        insert.setBackground(new java.awt.Color(153, 255, 102));
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        getContentPane().add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 432, -1, 30));

        delete.setBackground(new java.awt.Color(153, 255, 102));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 432, -1, 30));

        txtKalender.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txtKalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 145, -1));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 347, 145, -1));

        jLabel10.setText("Kondisi Cuaca");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 350, 95, -1));

        btnGambar.setBackground(new java.awt.Color(153, 255, 102));
        btnGambar.setText("Gambar");
        btnGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGambarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 432, -1, 30));
        getContentPane().add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 387, 145, -1));

        jLabel12.setText("ID");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 30, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 140, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas4/Background4.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        //
        try{
            
            Connection con = getConnection();
            String query = "INSERT into t_cuaca (tanggal,nama_kota,suhu,suhu_maks,suhu_min,kecepatan_angin,kelembapan,tekanan_udara,kondisi_cuaca,gambar) values (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(query);
            
            ps.setString(1, ((JTextField)txtKalender.getDateEditor().getUiComponent()).getText());
            ps.setString(2, txtNama.getText());
            ps.setString(3, txtSuhu.getText());
            ps.setString(4, txtMaks.getText());
            ps.setString(5, txtMin.getText());
            ps.setString(6, txtLembap.getText());
            ps.setString(7, txtAngin.getText());
            ps.setString(8, txtUdara.getText());
            ps.setString(9, status.getText());
            ps.setString(10, gambar.getText());
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Berhasil Di Input");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_insertActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            
            Connection con = getConnection();
            String query = "DELETE from t_cuaca where id=?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, id.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Berhasil Di Delete");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
}
    }//GEN-LAST:event_deleteActionPerformed

    private void btnGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambarActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser("E:\\KULIAH STMIK\\Pemrograman Visual\\UasModel\\src\\Picture\\");
        jfc.showOpenDialog(null);
        File file = jfc.getSelectedFile();
        String dir = file.getName();
        gambar.setText(dir);
    }//GEN-LAST:event_btnGambarActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGambar;
    private javax.swing.JButton delete;
    private javax.swing.JTextField gambar;
    private javax.swing.JTextField id;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField status;
    private javax.swing.JTextField txtAngin;
    private com.toedter.calendar.JDateChooser txtKalender;
    private javax.swing.JTextField txtLembap;
    private javax.swing.JTextField txtMaks;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSuhu;
    private javax.swing.JTextField txtUdara;
    // End of variables declaration//GEN-END:variables

    
}
