/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas4;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import tugas4.Cuaca;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author andrew
 */
public class FrmTugas extends javax.swing.JFrame {

    /**
     * Creates new form FrmTugas
     */
    public FrmTugas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        database = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        hasilDatabase = new javax.swing.JTextField();
        hasilUser = new javax.swing.JTextField();
        hasilPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Login Database");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        database.setText("Nama database");
        getContentPane().add(database, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 57, -1, -1));

        user.setText("Nama user");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 97, -1, -1));

        password.setText("Password user");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 137, -1, -1));
        getContentPane().add(hasilDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 54, 130, -1));
        getContentPane().add(hasilUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 94, 130, -1));
        getContentPane().add(hasilPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 134, 130, -1));

        jButton1.setBackground(new java.awt.Color(51, 255, 255));
        jButton1.setText("Koneksikan!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 183, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas4/Background6.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String a = hasilDatabase.getText();
       String b = hasilUser.getText();
       String c = hasilPassword.getText();
           try {
                   String host        = "jdbc:mysql://localhost/"+ a,
                          user        = b,
                          password    = c;
                   Connection con = (Connection) DriverManager.getConnection(host, user, password);
                   JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
                   
                   Cuaca frmCuaca = new Cuaca();
                   frmCuaca.setLocationRelativeTo(null);
                   frmCuaca.setVisible(true);
                  
           }catch(SQLException err){
                   JOptionPane.showMessageDialog(null,"Error");
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel database;
    private javax.swing.JTextField hasilDatabase;
    private javax.swing.JTextField hasilPassword;
    private javax.swing.JTextField hasilUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel password;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
